# Generated by Django 4.2.5 on 2023-10-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.PositiveIntegerField(verbose_name='ID чат в tg'),
        ),
    ]
