# Generated by Django 4.2.5 on 2023-10-14 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Место, в котором необходимо выполнять привычку.', max_length=255)),
                ('time', models.TimeField(help_text='Время, когда необходимо выполнять привычку.')),
                ('action', models.CharField(help_text='Действие, которое представляет из себя привычку.', max_length=255)),
                ('is_reward', models.BooleanField(default=False, help_text='Признак приятной привычки.')),
                ('frequency', models.CharField(default='daily', help_text='Периодичность выполнения привычки для напоминания в днях.', max_length=255)),
                ('reward', models.CharField(help_text='Вознаграждение за выполнение привычки.', max_length=255)),
                ('estimated_time', models.IntegerField(help_text='Время, которое предположительно потратит пользователь на выполнение привычки.')),
                ('is_public', models.BooleanField(default=False, help_text='Признак публичности привычки.')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Связанная привычка, если таковая имеется.', null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
