# Generated by Django 4.2.5 on 2023-10-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Еженедельная')], default='daily', help_text='Периодичность выполнения привычки для напоминания в днях.', max_length=255),
        ),
    ]
