# Generated by Django 4.2.5 on 2023-10-22 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='notification_time',
            field=models.CharField(choices=[('fifteen', 'За 15 минут'), ('thirty', 'За 30 минут'), ('hour', 'За час'), ('two_hours', 'За 2 часа'), ('day', 'За 24 часа')], default='thirty', help_text='За сколько присылать уведомления до начала привычки', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Еженедельная')], default='daily', help_text='Периодичность выполнения привычки для напоминания в днях.', max_length=20),
        ),
    ]
