# Generated by Django 4.2.5 on 2023-10-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0007_habit_is_starting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='date_of_creation',
            new_name='date_of_start',
        ),
    ]
