# Generated by Django 4.2.5 on 2023-10-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0008_rename_date_of_creation_habit_date_of_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='notification',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Еженедельная')], default='telegram', help_text='Тип оповощения telegram/email.', max_length=20),
        ),
    ]
