# Generated by Django 4.2.5 on 2023-10-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0009_habit_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='notification',
            field=models.CharField(choices=[('telegram', 'Телеграм'), ('email', 'Почта')], default='telegram', help_text='Тип оповощения telegram/email.', max_length=20),
        ),
    ]
